### PR TITLE
Cache which fields on entities are enums

### PR DESCRIPTION
**Pull request by VasekPurchart**

### CODE REVIEW

**Comment by VasekPurchart** [comment]
I did some testing and on my real data set of `40404` items these are average-ish times:

**Before:** (using `CachedReader`)
```
non-root@882d405ae8f5:/pocket-stats$ time bin/console
object(PocketStats\ApiBundle\Item\UserItemStatus)#538975 (1) {
  ["value":"Consistence\Enum\Enum":private]=>
  string(8) "archived"
}
int(40404)

real	0m10.553s
user	0m10.336s
sys	0m0.056s
```

**After:**
```
non-root@882d405ae8f5:/pocket-stats$ time bin/console
object(PocketStats\ApiBundle\Item\UserItemStatus)#538975 (1) {
  ["value":"Consistence\Enum\Enum":private]=>
  string(8) "archived"
}
int(40404)

real	0m9.846s
user	0m9.704s
sys	0m0.076s
```

Methodology was run it just after Kernel setup, just with loading from EM by findAll + iterate over them, so nothing scientific, but I think, the change is noticeable, seems like **`~10%` improvement**. I must note, that I consider this really not usual, because you are generally not supposed to use Doctrine with so many entities in one batch.

---

I was curious, how much overhead is there in the listener, so I put a return on the first line of it and got (again average-ish):

```
non-root@882d405ae8f5:/pocket-stats$ time bin/console
string(8) "archived"
int(40404)

real	0m9.744s
user	0m9.568s
sys	0m0.044s
```

You can see, that the enum is not "loaded".
So the implementation is really negligible, compared to the overall time.

**Comment by VasekPurchart** [comment]
cc @Majkl578, @jakub-klapka can you look at it/test it please? (+ see my testing above)

**Comment by jakub-klapka** [comment]
I did tests on real life project, where I hydrate around 7k entities as part of import job.
Comapred to v1.0, one job with this PR is 20% faster. Compared to version, where I don't have consistence-doctrine at all, it is 2% slower (which is within measurement error). So thumbs up for this one.

**Comment by VasekPurchart** [comment]
@jakub-klapka thanks a lot for the real-life data test 👍

**Pull request merged**
